### ISSUE TITLE
Extends!

### ISSUE THREAD

**Issue by emtudo** [artesaos-lab/defender-dashboard#19]
Uma  proposta para estender as view ao layout padrão.
==========
Exemplo da view:

@extends(config("dashboard.view.extends")?config("dashboard.view.view"):'dashboard::master')
@section(config("dashboard.view.extends")?config("dashboard.view.section"):'content')

Conteudo

@endsection
=====================================
Exemplo do config/dashboard.php
return [

    'prefix' => 'dashboard',
    'view' => [
    	'extends'	=>	false,
    	'view'		=>	'app',
    	'section'	=>	'content',
    ],
...
}

=================

estou igual o @vluzrmos não desisto nunca rsrrss

A propósito estou usando dessa mesma forma nos pacotes que comecei a desenvolver e achei legal.

**Comment by vluzrmos** [comment]
Não precisa disso @emtudo, 
você pode simplesmente sobrescrever a view em 
`resources/views/vendor/dashboard/nome-dessa-view-aí.blade.php`

Aí proponho que se renomeie o atalho do `dashboard` pra algo mais significativo como `defender-dashboard`. @andreoav

**Comment by emtudo** [comment]
Também. Mas ainda sou a favor de estender o layout

**Comment by emtudo** [comment]
O que vc não esta pensando no caso de sobrescrever é que se atualizar o pacote já era.

**Comment by vluzrmos** [comment]
Não tem pra onde correr. 
E por isso se usa versões estáveis dos pacotes (e fixas)

**Comment by andreoav** [comment]
Se vc atualiza o resources/views da sua aplicação, depois de fazer um
`vendor:publish:` das views, não vai sobrescrever a cada atualização.

Na verdade é justamente pra isso q serve publicar as views.

---------
Andreo de Aguiar Vieira
Desenvolvimento de Sistemas Java e PHP
Acadêmico do curso de Ciência da Computação - UFSM/RS

Em 1 de julho de 2015 12:00, Leandro Henrique Reis <notifications@github.com

**Comment by emtudo** [comment]
Se houver atualizações nas views do pacote mesmo sendo estável e fixa?

**Comment by vluzrmos** [comment]
Deve utilizar o sistema de Views do Blade. Se não quiser receber o update da view, basta não forçar a publicação das views  `vendor:publish --force` (**cuidado**). 
De qualquer forma, mesmo que utilizasse esse proposal, atualizar o pacote seria um risco a sua view personalizada.
