### ISSUE TITLE
Extends na view

### ISSUE THREAD

**Issue by emtudo** [artesaos-lab/defender-dashboard#7]
Poder estender a view para o layout padrão. Ou simplesmente ter um menu voltar para poder voltar ao sistema em questão.

**Comment by andreoav** [comment]
Extend no layout padrão creio q n seja a melhor opção, principalmente se o sistema que irá ser utilizado o dashboard não usar o Twitter Bootstrap.

Creio que uma opção para voltar ao sistema seja melhor.

**Comment by emtudo** [comment]
Pode ser condicional, e não obrigatório.
Mas a opção de um botão para voltar ao sistema já é alguma coisa :+1:

**Comment by emtudo** [comment]
Foi feito um link para voltar ao sistema.
